language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install PyMySQL . pytest mock codecov pexpect behave

script:
  - coverage run --source mycli -m py.test
  - cd tests
  - behave
  - cd ..

after_success:
  - coverage combine
  - codecov

notifications:
  webhooks:
    urls:
      - YOUR_WEBHOOK_URL
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
